### ISSUE TITLE
[question] have tried the other trackpad models without connector?

### ISSUE THREAD

**Issue by protobits** [vlukash/corne-trackpad#1]
I see several trackpad models available for similar price, from different BlackBerry versions. Some of these have simple exposed pads on the flexible PCB connector, which seems easier to solder against a PCB, not requiring the tiny hirose connector you used. Did you tried using one of these? I would like to buy and try one but I could not find a pinout for these. 
How did you found the pinout for your model?

Thank you!!

![image](https://user-images.githubusercontent.com/161706/62876966-79a2be80-bcfc-11e9-9f5b-9181cc9f4c52.png)

**Comment by vlukash** [comment]
Hi,

I considered only two trackpad models for this project - BB8520 and BB9900, as I wasn't able to find any documentation on other BB trackpads. I believe ([based on this link](https://forum.arduino.cc/index.php?topic=302036.msg2143236#msg2143236)) BB9900 uses I2C and 9520 uses SPI [(some details on Arduino forum](https://forum.arduino.cc/index.php?topic=61637.msg1754304#msg1754304)).
Also, I found a really good source [here](https://docs.greycat.co/trackpad.html#intro) for the 8520.

I'd be interested in any information on other BB modules. Please share if you get any updates!

Thanks!

**Comment by protobits** [comment]
I actually bough 9800 and 9900 sensors and made the 9800 work: https://hackaday.io/project/167075-thumbmouse
You are correct, both of these have same pinout and work over I2C.

I'm now struggling to find appropriate connectors. I believe I found one from I-Pex for the 9900 but none for the 9800.

**Comment by vlukash** [comment]
Glad to hear you've made the 9800 work!
Good luck with the project!

**Comment by tg-x** [comment]
> I believe I found one from I-Pex for the 9900 but none for the 9800.

@v01d do you have a link / part nr to the connector from i-pex?

looks like 9800/9900 is easier to find on ebay and would be great to be able to make it work with crkbd, 8250 seems more rare

**Comment by protobits** [comment]
Sorry for the late response, the part number I manage to find (can't verify if it is indeed compatible) is: 20599-013E-01

**Comment by protobits** [comment]
Actually, i will probably order soon a few connectors I've found on Mouser for the 9900 (0.3mm pitch): https://ar.mouser.com/ProductDetail/649-1061122131120HLF
I will use it to make a breakout board for it (including require regulators and level translators)

**Comment by mryndzionek** [comment]
Hello @v01d  and @vlukash. I would like to use 9800 trackpad in my project, but the schematics/pinouts on Arduino forum don't seem to be available anymore. I have two questions:

1.  what is `VSYS` pin ?
2.  what is the register/command that switches to 1000cpi ?

**Comment by protobits** [comment]
After some testing, I don't recommend the 9900/9800 series of trackpads since they required connector is not available. I tried one that looked similar but ended up having to modify it to fit. I think the trackpads which have the square mezzanine connector are much better and there are parts available. The ones with 20 pins are SPI and only require 2.8v supply. The 14 pin ones are I2C and require both 2.8v and 1.8v. I made a breakout for the I2C variants but have not tested it yet.

**Comment by protobits** [comment]
By the way, you may find my [thumbmouse](https://hackaday.io/project/167075-thumbmouse) project of interest, as it involves blackberry trackpads.

**Comment by mryndzionek** [comment]
Yes, I've seen your project @v01d. Actually your log is the best place that summarizes available information regarding the trackpads. I only have the 9800 available and I won't be using the connector for now. The only info I'm missing is:

 1. what is VSYS pin ?
 2. what is the register/command that switches to 1000cpi ?

Would you be able to answer those questions?

**Comment by protobits** [comment]
1. That pin supposedly is related to a LED which I'm not sure is supposed to be powered from that pin or that you should power it yourself. I've left it disconnected, it is not important. Note the description here: https://hackaday.io/project/167075/logs (9800 and 9900 have actually the same pinout)
2. I don't remember know which datasheet I've used for the 9900 but I believe all trackpads behave as a ADNS3530 (at least that is true for the 8520). So that would be register 0x11, bit 7 set to 1.

[ADNS-3530.pdf](https://github.com/vlukash/corne-trackpad/files/5446264/ADNS-3530.pdf)

A driver for the 8520 for NuttX is here: https://gitlab.com/nuttx_projects/bb_trackpad
It may be useful to understand how registers are used.

**Comment by shrekale** [comment]
Hey @vlukash I had an old BB Q20 from which I harvested the trackpad. Unfortunately, I lost the connector socket in the trash. Are these connectors available outside? I really don’t want to shuffle through my trashcan to find it 🤢

**Comment by shrekale** [comment]
Lost the connector, my question was about ordering one, but no worries, found it. I have Ferris Sweep+ NiceNanos & Old Blackberry Q20 trackpad. All I need is to design the breakout and order it. I am planning on double stacking it on the back of Nice!Nano. So, Nice!nano will have pins on one side and socket on the back of it, and the breakout will be exactly of that size which will get socketed on top. Lets see how that works, it's my first ever project that involves designing a PCB.

**Comment by stolen** [comment]
Hi guys. I'm late to the party, but maybe some current/future enthusiasts will find ths useful.

  * The chip is ADBS-A320, the datasheet is available online
  * 3.3v is OK, no 2.8v regulator needed
  * It has burst mode (it needs to be configured explicitly) and finger detection
  * Hirose FH35C-17S seems to be OK for 9900 (I don't have a board for it yet)

I've gathered some info in my repo: https://github.com/stolen/blackberry_trackpad
